# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20160427_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='score',
            field=models.FloatField(),
        ),
    ]
